spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: JOP_project
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:5432/example_database?currentSchema=jop
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: jop
