apiVersion: apps/v1
kind: Deployment
metadata:
  name: jop-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jop-project
  template:
    metadata:
      labels:
        app: jop-project
    spec:
      containers:
        - name: jop-project-container
          image: densold/jop_project
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: hostname
            - name: SPRING_DATASOURCE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: database
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: password
          volumeMounts:
            - name: photos-volume
              mountPath: /app/photos
      volumes:
        - name: photos-volume
          persistentVolumeClaim:
            claimName: photos-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: jop-service
spec:
  type: LoadBalancer
  selector:
    app: jop-project
  ports:
    - port: 80
      targetPort: 8080
